name: docsafe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  flutter_svg:
  dynamicutils:
  pinput:
  smooth_page_indicator:
  supabase_flutter :
  fluttertoast: ^8.2.2
  motion_toast:
  flutter_credit_card: ^4.0.1
  carousel_slider: ^4.2.1
  get_storage:
  permission_handler: ^11.1.0
  path_provider:
  image_picker:
  file_picker:
  syncfusion_flutter_pdfviewer: ^23.2.7
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow.ttf
