name: docsafe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  flutter_svg:
  dynamicutils:
  pinput:
  smooth_page_indicator:
  supabase_flutter:
  fluttertoast: ^8.2.2
  motion_toast:
  get_storage:
  permission_handler: ^11.1.0
  path_provider:
  image_picker:
  file_picker:
  open_file: ^3.3.2
  flutter_screen_lock: ^9.1.0
  screen_protector: ^1.4.2
  credit_card_scanner: ^1.0.5
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

ios:
  deployment_target: '9.0'

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow.ttf
