import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US' : {
      "docSafe" : "DocSafe",
      "welcome" : "Welcome",
      "create_account" : "Create Account",
      "sign_in" : "Sign In",
      "by_continuing,_you_agree_to_DSA's\t" : "By continuing, you agree to DSA's\t",
      "terms_&_conditions_&\n" : "Terms & Conditions &\n",
      "privacy_policy" : "Privacy Policy",
      "back" : "Back",
      "welcome_back!" : "Welcome Back!",
      "i’m_a_new_user!\t" : "I’m a new user!\t",
      "sign_up" : "Sign Up",
      "boost_productivity" : "Boost Productivity",
      "foc.io_helps_you_boost_your_productivity\non_a_different_level" : "Foc.io helps you boost your productivity\non a different level",
      "work_seamlessly" : "Work Seamlessly",
      "get_your_work_done_seamlessly\nwithout_interruption" : "Get your work done seamlessly\nwithout interruption",
      "achieve_higher_goals" : "Achieve Higher Goals",
      "by_boosting_your_productivity_we_help\nyou_achieve_higher_goals" : "By boosting your productivity we help\nyou achieve higher goals",
      "get_started" : "Get Started",
      "next" : "Next",
      "please_enter_email" : "Please Enter Email",
      "please_enter_valid_email" : "Please Enter Valid Email",
      "first_name" : "First Name",
      "last_name" : "Last Name",
      "email" : "Email",
      "please_enter_first_name" : "Please Enter First Name",
      "please_enter_last_name" : "Please Enter Last Name",
      "please_enter_last_name" : "Please Enter Last Name",
      "password" : "Password",
      "please_enter_password" : "Please Enter Password",
      "must_be_more_than_5_character" : "Must be more than 5 character",
      "forgot_password?" : "Forgot Password?",
      "confirm_password" : "Confirm Password",
      "not_match" : "Not Match",
      "hello,\t" : "Hello,\t",
      "my_space": "My Space",
      "rename":"Rename",
      "delete":"Delete",
      "pin":"Pin",
      "card" : "Card",
      "view_all" : "View All",
      "recently_used" : "Recently Used",
      "add_file_or_folder" : "Add File or Folder",
      "folder_name" : "Folder Name",
      "create_folder" : "Create Folder",
      "my_space_item" : "My Space Item",
      "card_holder_name" : "Card Holder's name",
      "card_number" : "Card Number",
      "add_card" : "Add Card",
      "expiry_date" : "Expiry Date",
      "security_code" : "Security Code",
      "save_to_wallet" : "Save To Wallet",
      "my_cards" : "My Cards",
    },
  };
}