import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US' : {
      "docSafe" : "DocSafe",
      "welcome" : "Welcome",
      "create_account" : "Create Account",
      "sign_in" : "Sign In",
      "by_continuing,_you_agree_to_DSA's\t" : "By continuing, you agree to DSA's\t",
      "terms_&_conditions_&\n" : "Terms & Conditions &\n",
      "privacy_policy" : "Privacy Policy",
      "back" : "Back",
      "welcome_back!" : "Welcome Back!",
      "i’m_a_new_user!\t" : "I’m a new user!\t",
      "sign_up" : "Sign Up",
      "boost_productivity" : "Boost Productivity",
      "foc.io_helps_you_boost_your_productivity\non_a_different_level" : "Foc.io helps you boost your productivity\non a different level",
      "work_seamlessly" : "Work Seamlessly",
      "get_your_work_done_seamlessly\nwithout_interruption" : "Get your work done seamlessly\nwithout interruption",
      "achieve_higher_goals" : "Achieve Higher Goals",
      "by_boosting_your_productivity_we_help\nyou_achieve_higher_goals" : "By boosting your productivity we help\nyou achieve higher goals",
      "get_started" : "Get Started",
      "next" : "Next",
      "please_enter_email" : "Please Enter Email",
      "please_enter_valid_email" : "Please Enter Valid Email",
      "first_name" : "First Name",
      "last_name" : "Last Name",
      "email" : "Email",
      "please_enter_first_name" : "Please Enter First Name",
      "please_enter_last_name" : "Please Enter Last Name",
      "password" : "Password",
      "please_enter_password" : "Please Enter Password",
      "must_be_more_than_5_character" : "Must be more than 5 character",
      "forgot_password?" : "Forgot Password?",
      "confirm_password" : "Confirm Password",
      "not_match" : "Not Match",
      "hello,\t" : "Hello,\t",
      "my_space": "My Space",
      "edit":"Edit",
      "rename":"Rename",
      "delete":"Delete",
      "pin":"Pin",
      "unpin":"Unpin",
      "card" : "Card",
      "view_all" : "View All",
      "recently_used" : "Recently Used",
      "add_file_or_folder" : "Add File or Folder",
      "folder_name" : "Folder Name",
      "create_folder" : "Create Folder",
      "my_space_item" : "My Space Item",
      "card_holder_name" : "Card Holder's name",
      "card_number" : "Card Number",
      "add_card" : "Add Card",
      "expiry_date" : "Expiry Date",
      "security_code" : "Security Code",
      "save_to_wallet" : "Save To Wallet",
      "my_cards" : "My Cards",
      "there" : "There !!",
      "you_do_not_have_a_PIN_card_yet." : "You do not have a PIN card yet.",
      "you_don't_have_any_pinned_documents" : "You don't have any pinned documents",
      "pin_card" : "Pin Card",
      "add_pin_document" : "Add Pin Documents",
      "enter_holder_name" : "Enter Holder Name",
      "enter_card_number" : "Enter Card Number",
      "enter_expiry_date" : "Enter Expiry Date",
      "enter_security_code" : "Enter Security Code",
      "language" : "Language",
      "enter_16_digits" : "Enter 16 Digits",
      "enter_3_digits" : "Enter 3 Digits",
      "scan_functionality_will_come_soon,\n_please_add_manually" : "Scan Functionality Will Come Soon, Please Add Manually",
    },

    'hi_IN' : {
      "docSafe" : "DocSafe",
      "welcome" : "स्वागत",
      "create_account" : "खाता बनाएं",
      "sign_in" : "दाखिल करना",
      "by_continuing,_you_agree_to_DSA's\t" : "जारी रखकर, आप डीएसए से सहमत हैं\t",
      "terms_&_conditions_&\n" : "नियम एवं शर्तें &\n",
      "privacy_policy" : "गोपनीयता नीति",
      "back" : "पीछे",
      "welcome_back!" : "वापसी पर स्वागत है!",
      "i’m_a_new_user!\t" : "मैं एक नया उपयोगकर्ता हूँ!\t",
      "sign_up" : "साइन अप करें",
      "boost_productivity" : "उत्पादकता बढ़ाएँ",
      "foc.io_helps_you_boost_your_productivity\non_a_different_level" : "Foc.io आपकी उत्पादकता बढ़ाने में आपकी मदद करता है\nएक अलग स्तर पर",
      "work_seamlessly" : "निर्बाध रूप से कार्य करें",
      "get_your_work_done_seamlessly\nwithout_interruption" : "अपना काम निर्बाध रूप से पूरा करें\nबिना किसी रुकावट के",
      "achieve_higher_goals" : "उच्च लक्ष्य प्राप्त करें",
      "by_boosting_your_productivity_we_help\nyou_achieve_higher_goals" : "आपकी उत्पादकता बढ़ाकर हम मदद करते हैं\nआप उच्च लक्ष्य प्राप्त करते हैं",
      "get_started" : "शुरू हो जाओ",
      "next" : "अगला",
      "please_enter_email" : "कृपया ईमेल दर्ज करें",
      "please_enter_valid_email" : "कृपया वैध ईमेल दर्ज़ करें",
      "first_name" : "पहला नाम",
      "last_name" : "उपनाम",
      "email" : "ईमेल",
      "please_enter_first_name" : "कृपया प्रथम नाम दर्ज करें",
      "please_enter_last_name" : "कृपया अंतिम नाम दर्ज करें",
      "password" : "पासवर्ड",
      "please_enter_password" : "कृपया पासवर्ड दर्ज करें",
      "must_be_more_than_5_character" : "5 से अधिक अक्षर होने चाहिए",
      "forgot_password?" : "पासवर्ड भूल गए?",
      "confirm_password" : "पासवर्ड की पुष्टि कीजिये",
      "not_match" : "मेल नहीं करता",
      "hello,\t" : "नमस्ते,\t",
      "my_space": "मेरी जगह",
      "edit":"संपादन करना",
      "delete":"मिटाना",
      "pin":"नत्थी करना",
      "unpin":"नत्थी खोल देना",
      "card" : "कार्ड",
      "view_all" : "सभी को देखें",
      "recently_used" : "हाल ही में उपयोग किया गया",
      "add_file_or_folder" : "फ़ाइल या फ़ोल्डर जोड़ें",
      "folder_name" : "फ़ोल्डर का नाम",
      "create_folder" : "फोल्डर बनाएं",
      "my_space_item" : "मेरा जगह आइटम",
      "card_holder_name" : "कार्डधारक का नाम",
      "card_number" : "कार्ड संख्या",
      "add_card" : "कार्ड जोड़ें",
      "expiry_date" : "समाप्ति तिथि",
      "security_code" : "सुरक्षा कोड",
      "save_to_wallet" : "वॉलेट में सहेजें",
      "my_cards" : "मेरे कार्ड",
      "there" : "वहाँ !!",
      "you_do_not_have_a_PIN_card_yet." : "आपका अभी तक कोई पिन कार्ड नहीं है।",
      "you_don't_have_any_pinned_documents" : "आपका  कोई पिन किया हुआ दस्तावेज़ नहीं है",
      "pin_card" : "पिन कार्ड",
      "add_pin_document" : "पपिन दस्तावेज़ जोड़ें",
      "enter_holder_name" : "धारक का नाम दर्ज करें",
      "enter_card_number" : "कार्ड नंबर दर्ज करें",
      "enter_expiry_date" : "समाप्ति तिथि दर्ज करें",
      "enter_security_code" : "सुरक्षा कोड डालें",
      "enter_16_digits" : "16 अंक दर्ज करें",
      "enter_3_digits" : "3 अंक दर्ज करें",
      "scan_functionality_will_come_soon,\n_please_add_manually" : "स्कैन कार्यक्षमता जल्द ही आएगी,\nकृपया मैन्युअल रूप से जोड़ें",
      "language" : "भाषां",
    },
  };
}